#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=64gb,walltime=4:00:00
#PBS -N app-AFQ
#PBS -V

set -e

echo "running AFQ"
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
if [ ! -s output.mat ];
then
	echo "output missing"
	exit 1
fi

echo "running AFQ"
time singularity exec -e docker://brainlife/afq-browser:1.0 afqbrowser-assemble \
    --page-title "title" \
    --page-subtitle "subtitle" \
    --page-title-link "link title" \
    --page-subtitle-link "link subtitle" \
    output.mat

